version: "3"  
services:
  web: 
    build:
      context: ./Intranet/Web
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.2
    dns: 192.168.0.4

  db:
    build:
      context: ./Intranet/DB
      dockerfile: Dockerfile
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
        #volumes:
        #- ./:/var/lib/mysql
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.3
    dns: 192.168.0.4

  soa:
    build:
      context: ./Intranet/SOA
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.4

  dns:
    build:
      context: ./Intranet/DNS
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.5

  mail:
    build: 
      context: Public/Mail-Server
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.6
    dns: 192.168.0.11
    ports:
      - 25:25
    volumes:
      - mailbox:/home/contact/Maildir

  contact:
    build:
      context: Public/Client-Mail-Contact
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.8
    dns: 192.168.0.4
    tty: true

  b2b:
    build:
      context: Public/Client-Mail-B2B
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.9
    dns: 192.168.0.11
    tty: true
  webpub: 
    build:
      context: ./Public/Web
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.10
    dns: 192.168.0.4

  soapub:
    build:
      context: ./Public/SOA
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.11
        
networks:
  trusted-zone:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          #          gateway: 192.168.0.1

volumes:
  db-data:
  mailbox:
