version: "3"  
services:
  web: 
    build:
      context: ./Intranet/Web
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.2

  db:
    build:
      context: ./Intranet/DB
      dockerfile: Dockerfile
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.3

  dns:
    build:
      context: ./Intranet/DNS
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.4

  soa:
    build:
      context: ./Intranet/SOA
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 192.168.0.5

networks:
  trusted-zone:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
  db-data:
