FROM trafex/php-nginx

COPY intranet.woodytoys.lab/ /var/www/intranet.woodytoys.lab/html/
COPY intranet.woodytoys.lab.conf /etc/nginx/sites-enabled/intranet.woodytoys.lab.conf
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

